name: pub_check_updates
description: check your pub package's updates
version: 0.0.1

executables:
  pcu: main

author: Nighting99 <nighting99@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.1

  dio: ^3.0.8

  path: ^1.6.3

  pub_semver: ^1.4.2

  yaml: ^2.2.0
